swagger: "2.0"
info:
  title: "FruitSellerApplicationUMS"
  description: "Service managing User Interactions in Fruit Selling Application"
  version: "0.0.1"
host: "$(SERVICE_HOST)"
basePath: /tms
schemes:
  - "http"
securityDefinitions:
  BasicAuth:
    type: apiKey
    in: header
    name: authorization
paths:
  /health:
    get:
      tags:
        - "Health endpoint"
      summary: "Returns health of service"
      produces:
        - "application/json"
      responses:
        200:
          description: "Server is alive, db connection is successful"
        424:
          description: "Server is alive, db is down"
        500:
          description: "Server is alive, db false"
  /register:
    post:
      tags:
        - "User Management"
      summary: "Registers a new user"
      produces:
        - "application/json"
      consumes:
        - "application/json"
      responses:
        201:
          description: "User Created Successfully"
        400:
          description: "Bad Request"
        409:
          description: "User already exists"
        500:
          description: "Internal Server Error"

  /login:
    post:
      tags:
        - "User Management"
      summary: "Log in a user"
      produces:
        - "application/json"
      consumes:
        - "application/json"
      responses:
        200:
          description: "Logged in successfully"
        400:
          description: "Bad Request"
        401:
          description: "Unauthorized"
        404:
          description: "User not found"
        500:
          description: "Internal Server Error"
  /getUser/:id:
    get:
      tags:
        - "User Management"
      summary: "Gets a user by ID"
      produces:
        - "application/json"
      responses:
        200:
          description: "User fetched successfully"
        400:
          description: "Bad Request"
        404:
          description: "User not found"
        500:
          description: "Internal Server Error"

  /putUser:
    put:
      tags:
        - "User Management"
      summary: "Updates a user by ID"
      produces:
        - "application/json"
      consumes:
        - "application/json"
      responses:
        200:
          description: "User updated successfully"
        400:
          description: "Bad Request"
        404:
          description: "User not found"
        500:
          description: "Internal Server Error"

  /patchUser:
    patch:
      tags:
        - "User Management"
      summary: "Partially updates a user by ID"
      produces:
        - "application/json"
      consumes:
        - "application/json"
      responses:
        200:
          description: "User updated successfully"
        400:
          description: "Bad Request"
        404:
          description: "User not found"
        500:
          description: "Internal Server Error"

  /deleteUser:
    delete:
      tags:
        - "User Management"
      summary: "Deletes a user by ID"
      produces:
        - "application/json"
      responses:
        200:
          description: "User deleted successfully"
        400:
          description: "Bad Request"
        404:
          description: "User not found"
        500:
          description: "Internal Server Error"