// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package userTokenProto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TokenGrpcServiceClient is the client API for TokenGrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TokenGrpcServiceClient interface {
	VerifyToken(ctx context.Context, in *VerifyTokenRequest, opts ...grpc.CallOption) (*VerifyTokenResponse, error)
	GenerateToken(ctx context.Context, in *GenerateTokenRequest, opts ...grpc.CallOption) (*GenerateTokenResponse, error)
}

type tokenGrpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenGrpcServiceClient(cc grpc.ClientConnInterface) TokenGrpcServiceClient {
	return &tokenGrpcServiceClient{cc}
}

func (c *tokenGrpcServiceClient) VerifyToken(ctx context.Context, in *VerifyTokenRequest, opts ...grpc.CallOption) (*VerifyTokenResponse, error) {
	out := new(VerifyTokenResponse)
	err := c.cc.Invoke(ctx, "/userTokenProto.TokenGrpcService/VerifyToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenGrpcServiceClient) GenerateToken(ctx context.Context, in *GenerateTokenRequest, opts ...grpc.CallOption) (*GenerateTokenResponse, error) {
	out := new(GenerateTokenResponse)
	err := c.cc.Invoke(ctx, "/userTokenProto.TokenGrpcService/GenerateToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenGrpcServiceServer is the server API for TokenGrpcService service.
// All implementations must embed UnimplementedTokenGrpcServiceServer
// for forward compatibility
type TokenGrpcServiceServer interface {
	VerifyToken(context.Context, *VerifyTokenRequest) (*VerifyTokenResponse, error)
	GenerateToken(context.Context, *GenerateTokenRequest) (*GenerateTokenResponse, error)
	mustEmbedUnimplementedTokenGrpcServiceServer()
}

// UnimplementedTokenGrpcServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTokenGrpcServiceServer struct {
}

func (UnimplementedTokenGrpcServiceServer) VerifyToken(context.Context, *VerifyTokenRequest) (*VerifyTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyToken not implemented")
}
func (UnimplementedTokenGrpcServiceServer) GenerateToken(context.Context, *GenerateTokenRequest) (*GenerateTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateToken not implemented")
}
func (UnimplementedTokenGrpcServiceServer) mustEmbedUnimplementedTokenGrpcServiceServer() {}

// UnsafeTokenGrpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TokenGrpcServiceServer will
// result in compilation errors.
type UnsafeTokenGrpcServiceServer interface {
	mustEmbedUnimplementedTokenGrpcServiceServer()
}

func RegisterTokenGrpcServiceServer(s grpc.ServiceRegistrar, srv TokenGrpcServiceServer) {
	s.RegisterService(&TokenGrpcService_ServiceDesc, srv)
}

func _TokenGrpcService_VerifyToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenGrpcServiceServer).VerifyToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userTokenProto.TokenGrpcService/VerifyToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenGrpcServiceServer).VerifyToken(ctx, req.(*VerifyTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenGrpcService_GenerateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenGrpcServiceServer).GenerateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userTokenProto.TokenGrpcService/GenerateToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenGrpcServiceServer).GenerateToken(ctx, req.(*GenerateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TokenGrpcService_ServiceDesc is the grpc.ServiceDesc for TokenGrpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TokenGrpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "userTokenProto.TokenGrpcService",
	HandlerType: (*TokenGrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyToken",
			Handler:    _TokenGrpcService_VerifyToken_Handler,
		},
		{
			MethodName: "GenerateToken",
			Handler:    _TokenGrpcService_GenerateToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "userTokenProto/token.proto",
}
